filter:
    paths:
        - 'packages/*'
checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: false
            within:
                brackets: true
